apiVersion: v1
kind: Namespace
metadata:
  name:  webapp
---
apiVersion: v1
kind: Secret
metadata:
  name:  dbsecret
  namespace: webapp
data:
   DB_PWD: cm9vdA==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfigmap
  namespace: webapp
data:
  DB_PORT: "3306"
  DB_USER: root
  DB_DRIVER: com.mysql.cj.jdbc.Driver
  DB_DB: bankappdb
  DB_HOST: db-service
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: db-deploy
    namespace: webapp
  spec:
    replicas: 2
    selector:
      matchLabels:
        mysql: db
    template:
      metadata:
        labels:
          mysql: db
      spec:
        containers:
        - name: mysql
          image: sqldb
          ports:
          - containerPort: 3306
            name: dbsvc
          resources:
            requests:
              cpu: "600m"
              memory: "1700Mi"
            limits:
              cpu: "800m"
              memory: "1900Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: DB_PWD
          volumeMounts:
            - name:  db-volume
              mountPath: /var/lib/mysql
        volumes:
          - name: db-volume
            hostPath:
              path: /root/ubuntu/bank
---
apiVersion: v1
kind: Service
metadata:
  name:  db-service
  namespace: webapp
spec:
  selector:
    mysql: db
  type:  ClusterIP
  ports:
  - name:  dbservice-redirect
    port:  3306
    targetPort:  dbsvc
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: front-end
  name: front-end
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-end
    spec:
      containers:
      - image: venkaiahk/web:v1
        name: web
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_USER
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_PORT
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_HOST
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_PWD
---
kind: Service
apiVersion: v1
metadata:
  name:  app-svc
  namespace: webapp
spec:
  selector:
    app:  bank
  type:  LoadBalancer
  ports:
  - name:  allow-http
    port:  80
    targetPort:  appsvc