
apiVersion: v1
kind: Secret
metadata:
  name:  dbsecret
data:
   DB_PWD: cm9vdA==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfigmap
data:
  DB_PORT: "3306"
  DB_USER: root
  DB_DRIVER: com.mysql.cj.jdbc.Driver
  DB_DB: bankappdb
  DB_HOST: db-service
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: db-deploy
  spec:
    serviceName: db-service
    replicas: 1
    selector:
      matchLabels:
        mysql: db
    template:
      metadata:
        labels:
          mysql: db
      spec:
        containers:
        - name: mysql
          image: mysql:8.0
          ports:
          - containerPort: 3306
            name: dbsvc
          resources:
            requests:
              cpu: "600m"
              memory: "1700Mi"
            limits:
              cpu: "800m"
              memory: "1900Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: DB_PWD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: dbconfigmap
                  key: DB_DB

          volumeMounts:
            - name:  db-volume
              mountPath: /var/lib/mysql
        volumes:
          - name: db-volume
            hostPath:
              path: /tmp/bank
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    mysql: db
  clusterIP: None
  ports:
  - name:  dbservice-redirect
    port:  3306
    targetPort:  dbsvc
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-end
    spec:
      containers:
      - image: venkaiahk/web:v1
        name: front-end-app
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_USER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_PWD
        - name: DB_DRIVER
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_DRIVER 
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: dbconfigmap
              key: DB_DB
---
kind: Service
apiVersion: v1
metadata:
  name:  app-svc
spec:
  selector:
    app: front-end
  type: NodePort
  ports:
  - name: allow-http
    port: 80
    targetPort: web