spring.application.name=bankapp
# MySQL Database configuration
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:{DB_PORT:3306}/${DB_NAME:bankappdb}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PWD:Test@123}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA & Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
